### ISSUE TITLE
Relative url() paths are being rewritten

### ISSUE THREAD

**Issue by snaptopixel** [ionic-team/stencil-stylus#1]
I'm trying to use `@font-face` and would prefer NOT to embed the fonts due to file size, etc. I've noticed that when using relative paths the plugin is adding the css file's path in the src directory which makes it unusable.

I believe this could be remedied by adding something like an `assetsUrl` or `rootPath` to the config...

**Before compilation**
> src/styles/global.styl
```stylus
@font-face
  font-family 'proxima-nova'
  font-weight 100
  src url(assets/fonts/proxima_nova_thin.woff2) format('woff2'),
      url(assets/fonts/proxima_nova_thin.woff) format('woff')
```

**After compilation**
```css
@font-face {
  font-family: proxima-nova;
  font-weight: 100;
  src: url(src/styles/assets/fonts/proxima_nova_thin.woff2) format('woff2'), url(src/styles/assets/fonts/proxima_nova_thin.woff) format('woff')
}
```
